<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Copyright>Copyright © 2026</Copyright>
    <Product>AudioBoarder</Product>
    <Version>0.6.1</Version>
  </PropertyGroup>
</Project>
