<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Copyright>Copyright © 2026</Copyright>
    <Product>AudioBoarder</Product>
    <Version>0.8.0-preview.2</Version>
    <RepositoryUrl>https://github.com/oguzhanf/audioboarder</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <UpdateAllowedSignerCertificateSha256 Condition="'$(UpdateAllowedSignerCertificateSha256)' == ''"></UpdateAllowedSignerCertificateSha256>
    <PortableBuild Condition="'$(PortableBuild)' == ''">false</PortableBuild>
  </PropertyGroup>
</Project>
