<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AudioBoarder.Core</RootNamespace>
    <AssemblyName>AudioBoarder.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AudioBoarder.Tests" />
  </ItemGroup>

</Project>
